name: Ruby

on:
  push:
    branches: [ master, http ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install system dependencies
      run: sudo apt-get --yes install libidn11-dev
    - name: Install ruby dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake